/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
export type { DataDecode } from "./DataDecode";
export type { TokenTransfer } from "./TokenTransfer";
export type { TransferCall } from "./TransferCall";
