/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SwoshInterface extends utils.Interface {
  functions: {
    "batchTransferERC1155(address[],address,uint256[],uint256[])": FunctionFragment;
    "batchTransferERC20(address[],address,uint256[])": FunctionFragment;
    "batchTransferERC721(address[],address,uint256[])": FunctionFragment;
    "megaTransfer(address[],address[],uint256[],uint256)": FunctionFragment;
    "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])": FunctionFragment;
    "multiBatchTransferERC20(address[],address[],uint256[])": FunctionFragment;
    "multiBatchTransferERC721(address[],address[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchTransferERC1155"
      | "batchTransferERC1155(address[],address,uint256[],uint256[])"
      | "batchTransferERC20"
      | "batchTransferERC20(address[],address,uint256[])"
      | "batchTransferERC721"
      | "batchTransferERC721(address[],address,uint256[])"
      | "megaTransfer"
      | "megaTransfer(address[],address[],uint256[],uint256)"
      | "multiBatchTransferERC1155"
      | "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"
      | "multiBatchTransferERC20"
      | "multiBatchTransferERC20(address[],address[],uint256[])"
      | "multiBatchTransferERC721"
      | "multiBatchTransferERC721(address[],address[],uint256[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchTransferERC1155",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferERC1155(address[],address,uint256[],uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferERC20",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferERC20(address[],address,uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferERC721",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferERC721(address[],address,uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "megaTransfer",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "megaTransfer(address[],address[],uint256[],uint256)",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC1155",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC20",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC20(address[],address[],uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC721",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiBatchTransferERC721(address[],address[],uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchTransferERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferERC1155(address[],address,uint256[],uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferERC20(address[],address,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferERC721(address[],address,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "megaTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "megaTransfer(address[],address[],uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC20(address[],address[],uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiBatchTransferERC721(address[],address[],uint256[])",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Swosh extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwoshInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "batchTransferERC1155(address[],address,uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "batchTransferERC20(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "batchTransferERC721(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    megaTransfer(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "megaTransfer(address[],address[],uint256[],uint256)"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiBatchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiBatchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multiBatchTransferERC20(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiBatchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multiBatchTransferERC721(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  batchTransferERC1155(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "batchTransferERC1155(address[],address,uint256[],uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTransferERC20(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "batchTransferERC20(address[],address,uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchTransferERC721(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "batchTransferERC721(address[],address,uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipient: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  megaTransfer(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _offset: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "megaTransfer(address[],address[],uint256[],uint256)"(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    _offset: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiBatchTransferERC1155(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiBatchTransferERC20(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multiBatchTransferERC20(address[],address[],uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiBatchTransferERC721(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multiBatchTransferERC721(address[],address[],uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _recipients: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchTransferERC1155(address[],address,uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchTransferERC20(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchTransferERC721(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    megaTransfer(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "megaTransfer(address[],address[],uint256[],uint256)"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    multiBatchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    multiBatchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiBatchTransferERC20(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    multiBatchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiBatchTransferERC721(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    batchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "batchTransferERC1155(address[],address,uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "batchTransferERC20(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "batchTransferERC721(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    megaTransfer(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "megaTransfer(address[],address[],uint256[],uint256)"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiBatchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiBatchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multiBatchTransferERC20(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiBatchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multiBatchTransferERC721(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "batchTransferERC1155(address[],address,uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "batchTransferERC20(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "batchTransferERC721(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipient: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    megaTransfer(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "megaTransfer(address[],address[],uint256[],uint256)"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      _offset: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiBatchTransferERC1155(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multiBatchTransferERC1155(address[],address[],uint256[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiBatchTransferERC20(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multiBatchTransferERC20(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiBatchTransferERC721(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multiBatchTransferERC721(address[],address[],uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _recipients: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
