/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TokenTransferInterface extends utils.Interface {
  functions: {
    "multi721Transfer(address,address,uint256[])": FunctionFragment;
    "multiRecipientTransfer(address,address[],uint256[])": FunctionFragment;
    "multiTokenTransfer(address[],address,uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "multi721Transfer"
      | "multi721Transfer(address,address,uint256[])"
      | "multiRecipientTransfer"
      | "multiRecipientTransfer(address,address[],uint256[])"
      | "multiTokenTransfer"
      | "multiTokenTransfer(address[],address,uint256[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "multi721Transfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multi721Transfer(address,address,uint256[])",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiRecipientTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiRecipientTransfer(address,address[],uint256[])",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiTokenTransfer",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiTokenTransfer(address[],address,uint256[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "multi721Transfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multi721Transfer(address,address,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiRecipientTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiRecipientTransfer(address,address[],uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiTokenTransfer(address[],address,uint256[])",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TokenTransfer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenTransferInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    multi721Transfer(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multi721Transfer(address,address,uint256[])"(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiRecipientTransfer(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multiRecipientTransfer(address,address[],uint256[])"(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiTokenTransfer(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multiTokenTransfer(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  multi721Transfer(
    _token: PromiseOrValue<string>,
    _receiver: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multi721Transfer(address,address,uint256[])"(
    _token: PromiseOrValue<string>,
    _receiver: PromiseOrValue<string>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiRecipientTransfer(
    _token: PromiseOrValue<string>,
    _receivers: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multiRecipientTransfer(address,address[],uint256[])"(
    _token: PromiseOrValue<string>,
    _receivers: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiTokenTransfer(
    _tokens: PromiseOrValue<string>[],
    _receiver: PromiseOrValue<string>,
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multiTokenTransfer(address[],address,uint256[])"(
    _tokens: PromiseOrValue<string>[],
    _receiver: PromiseOrValue<string>,
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    multi721Transfer(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multi721Transfer(address,address,uint256[])"(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    multiRecipientTransfer(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiRecipientTransfer(address,address[],uint256[])"(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    multiTokenTransfer(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multiTokenTransfer(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    multi721Transfer(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multi721Transfer(address,address,uint256[])"(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiRecipientTransfer(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multiRecipientTransfer(address,address[],uint256[])"(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiTokenTransfer(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multiTokenTransfer(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multi721Transfer(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multi721Transfer(address,address,uint256[])"(
      _token: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiRecipientTransfer(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multiRecipientTransfer(address,address[],uint256[])"(
      _token: PromiseOrValue<string>,
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiTokenTransfer(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multiTokenTransfer(address[],address,uint256[])"(
      _tokens: PromiseOrValue<string>[],
      _receiver: PromiseOrValue<string>,
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
