/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
import type * as presets from "./presets";
export type { presets };
export type { ERC1155 } from "./ERC1155";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Receiver } from "./IERC1155Receiver";
