/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Burnable__factory } from "./ERC1155Burnable__factory";
export { ERC1155Pausable__factory } from "./ERC1155Pausable__factory";
export { IERC1155MetadataURI__factory } from "./IERC1155MetadataURI__factory";
